### PR TITLE
fix: going back when creating or editing map fixed

### LINKED ISSUE #81: When creating new map, you can't return from step 2 to step 1
When I wanted to create a new map but in the meantime decided to change its name (wanted to switch from step 2 to step 1), the back button didn't work.

## Description

User cannot take a step back when creating new map. I was able to change step on the top view of map creation (clicking on step's name) but app was already crashed in the background and showed error console.
[TIP]:  # CreateMap.js:137 Uncaught (in promise) TypeError: Cannot read property 'accountId' of null

## Steps to Reproduce

Open GeoOps app -> start creating a new map -> provide a name -> click next -> try to return to the previous step

## Expected Behaviour

It should allow us to return to the previous step and change i.e. name or default coords, zoom, etc.

## Relevant Logs / Console output

CreateMap.js:137 Uncaught (in promise) TypeError: Cannot read property 'accountId' of null

## Your Environment

* NR1 CLI version used: 1.22.2
* Browser name and version: Chrome 83
* Operating System and version: macOS 10.15.5

### PR DESCRIPTION
**Pull request by norbertsuski**
Closes #81 

I also removed manual binding in constructor as it's no longer necessary when using arrow functions.

### CODE REVIEW

File: nerdlets/geo-ops-nerdlet/CreateMap.js [hunk 1]
```diff
@@ -66,35 +65,31 @@ export default class CreateMap extends React.PureComponent {
       mapFormData: {}
     };
 
-    this.onAddEditMap = this.onAddEditMap.bind(this);
```
Comment (madecki) [inline nerdlets/geo-ops-nerdlet/CreateMap.js:69]: 👍
